name: Update Pet

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at 00:00 UTC
  workflow_dispatch:

jobs:
  update-pet:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Pet ðŸ‘¾
        uses: ./ # Uses the action in the current directory
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          username: ${{ github.repository_owner }}
          # Advanced Configuration
          timezone: "America/New_York"
          background_theme: "minimal"
          show_level: "true"

      - name: Commit and Push ðŸ’¾
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add dist/pet.svg
          git commit -m "Update Profile-Gotchi ðŸ‘¾" || exit 0
          git push
